#!/usr/sbin/nft -f
# Bloqueo de red

flush ruleset

table inet contest_lockdown {
    set allow4 { type ipv4_addr; flags interval; }
    set allow6 { type ipv6_addr; flags interval; }
    set dns4   { type ipv4_addr; }
    set dns6   { type ipv6_addr; }
    set ntp4   { type ipv4_addr; }

    chain input {
        type filter hook input priority 0; policy drop;
        iif "lo" accept
        ct state established,related accept
        ct state invalid drop
        udp sport 67 udp dport 68 accept          # respuestas DHCP
        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;   # sin bridging / ICS
    }

    # DNS forzado: toda consulta al puerto 53 van al resolver
    chain dns_redirect {
        type nat hook output priority -100; policy accept;
    }

    chain output {
        type filter hook output priority 0; policy drop;
        oif "lo" accept
        ct state established,related accept
        ct state invalid drop

        udp sport 68 udp dport 67 accept          # peticiones DHCP

        # DNS solo a los resolvers fijados
        ip  daddr @dns4 udp dport 53 accept
        ip  daddr @dns4 tcp dport 53 accept
        ip6 daddr @dns6 udp dport 53 accept
        ip6 daddr @dns6 tcp dport 53 accept

        # NTP: hora correcta = validacion TLS correcta
        ip daddr @ntp4 udp dport 123 accept

        # Sitios y servicios permitidos
        ip  daddr @allow4 accept
        ip6 daddr @allow6 accept

        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        limit rate 5/second log prefix "contest-drop " counter
    }
}
