#!/usr/bin/env bash

# Build identity
ISO_NAME="icpc-bolivia-debian"
ARCH="amd64"

# Base system
DEBIAN_SUITE="trixie"
DEBIAN_MIRROR="http://deb.debian.org/debian"
DEBIAN_SECURITY_MIRROR="http://security.debian.org/debian-security"
DEBIAN_COMPONENTS="main contrib non-free non-free-firmware"

# Branding
META_DISTRO_ID="icpc-bolivia-debian"
META_DISTRO_NAME="ICPC Bolivia Debian"
META_DISTRO_VERSION="13"

# Paths
PROJECT_TMP_DIR="${PROJECT_DIR}/tmp"
OUTPUT_DIR="${PROJECT_TMP_DIR}/output"
UPDATES_DIR="${PROJECT_TMP_DIR}/updates"
WORK_DIR="${PROJECT_TMP_DIR}/work"
ROOTFS_DIR="${WORK_DIR}/rootfs"
RUNTIME_DIR="${WORK_DIR}/runtime"
ISO_STAGING_DIR="${WORK_DIR}/iso-staging"
DOWNLOAD_CACHE_DIR="${PROJECT_TMP_DIR}/download-cache"
APT_CACHE_DIR="${PROJECT_TMP_DIR}/apt-cache"
DOWNLOAD_CONNECTIONS="8"
OUTPUT_RUNTIME="0"

# Local VM test defaults
DISK_SIZE_GB="20"
VM_NAME="icpc-bolivia-debian"
LAB_DISK_PATH="${PROJECT_TMP_DIR}/libvirt/images/icpc-bolivia-debian-lab-hdd.qcow2"
WIN_XP_DISK="${PROJECT_DIR}/Windows XP.qcow2"
WIN_XP_VM_NAME="icpc-winxp-lab"
ISO_PATH=""

# Runtime folder found by initramfs and GRUB
CONTEST_DIR="icpc_bo"
ROOT_SQUASH_NAME="filesystem.squashfs"

# Full installer bootstrap configuration
FULL_INSTALL_URL="http://192.168.122.1:8081/remote/full-install-bootstrap.sh"
FULL_INSTALL_SHA256=""
UPDATE_MANIFEST_URL="http://192.168.122.1:8081/updates/manifest.json"
UPDATE_CHECK_ON_BOOT="true"
RUNTIME_VERSION="dev"
AUTH_SERVICE_URL="https://login.codi.com.bo/login"
AUTH_SERVICE_TIMEOUT="20"
OPT_CONTEST_DIR="/opt/icpc"
ICP_REPORT_URL="https://stats.codi.com.bo/report"
ICP_REPORT_TIMEOUT="20"
STATS_LOG_SINCE="5 minutes ago"
STATS_REPORT_ON_BOOT="2min"
STATS_REPORT_INTERVAL="5min"

# System defaults
DESKTOP_PROFILE="${DESKTOP_PROFILE:-gnome}"
HOSTNAME="contest"
LOCALE="en_US.UTF-8"
SUPPORTED_LOCALES="en_US.UTF-8 es_ES.UTF-8 es_BO.UTF-8"
TIMEZONE="America/La_Paz"
DEFAULT_USER="icpc"
DEFAULT_PASSWORD="icpc"
ENABLE_AUTOLOGIN="true"
DEFAULT_BROWSER_URL="file:///usr/share/doc/contest/index.html"
GNOME_INPUT_SOURCES="[('xkb', 'latam'), ('xkb', 'us')]"
MIN_RAM_MB=""

# Keyboard layout (X11/GNOME + console)
# Use 'latam' for Spanish Latin American, 'es' for Spain, 'us' for US, etc.
KEYBOARD_LAYOUT="latam"

# Optional proxy, IP of the host                                                                                                                       
APT_PROXY="http://192.168.122.1:3142"
